
server:
  port: 5555

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
    
management:  endpoints:    web:      exposure:        include:        - routes

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  ribbon:
    ConnectTimeout: 10000000
    ReadTimeout: 10000000